In [2]:
# Task 5 implement 6 functions of matrix

# A Square Matrix
def is_square(M):
    (nrow,ncolumn) = M.shape
    if (nrow == ncolumn):
        return True
    else: 
        return False

    
# A Symmetrical Matrix
def is_symmetrical(M):
    (nrow,ncolumn) = M.shape
    if (is_square(M) == True):
        for i in range(0,nrow):
            for j in range(i+1,ncolumn):
                if (M[i,j] != M[j,i]):
                    return False
                else:
                    pass
        # end-loop
    else:
        return False
    # end-if
    return True


# A Diagonal Matrix
def is_diagonal(M):
    (nrow,ncolumn) = M.shape
    if (is_square(M) == True):
        for i in range(0,nrow):
            for j in range(i+1,ncolumn):
                if (M[i,j] != 0 or M[j,i] != 0):
                    return False
                else:
                    pass
        # end-loop
    else:
        return False
    # end-if
    return True
    

# An Identity Matrix
def is_identify(M):
    (nrow,ncolumn) = M.shape
    if (is_diagonal(M) == True):
        for i in range(0,nrow):
            if (M[i,i] != 1):
                return False
            else: 
                pass
    else: 
        return False
    # end-if
    return True


# A Zero Matrix
def is_zero(M):
    (nrow,ncolumn) = M.shape
    for i in range(0,nrow):
        for j in range(0,ncolumn):
            if (M[i,j] != 0):
                return False
            else: 
                pass
    # end-loop
    return True
    
    
# Matrix Transpose
def transpose(M):
    (nrow,ncolumn) = M.shape
    a = [[0]*nrow for i in range(ncolumn)] # new list to be a result
    for i in range(0,nrow):
        for j in range(0,ncolumn):
            a[j][i] = M[i,j]
    # end-loop
    return a
    
    

In [3]:
import numpy as np

A = np.matrix([[2,0,1],
               [2,5,0],
               [0,3,6],
               [1,3,6]
              ])

# is_square(A)
# is_symmetrical(A)
# is_diagonal(A)
print('Matrix A:\n',A)
print('Transpose of A:\n',np.matrix(transpose(A)))

Matrix A:
 [[2 0 1]
 [2 5 0]
 [0 3 6]
 [1 3 6]]
Transpose of A:
 [[2 2 0 1]
 [0 5 3 3]
 [1 0 6 6]]


In [4]:
# Task 6 Mutiplication

def multiply(A, B):
    (nrow_A,ncolumn_A) = A.shape 
    (nrow_B,ncolumn_B) = B.shape
    M = [[0]*ncolumn_B for i in range(nrow_A)] # new list as a result
    if (ncolumn_A == nrow_B):
        i = 0
        while (i < nrow_A):
            j = 0
            while (j < ncolumn_B):
                sum = k = 0
                while (k < ncolumn_A):
                    product = A[i,k]*B[k,j]
                    sum += product
                    k += 1
                # end-loop
                M[i][j] = sum
                j += 1
            # end-loop
            i += 1
        # end-loop
    else:
        print('Cannot multiply!')
    return M



In [5]:
import numpy as np

A = np.matrix([[2,1,1],
               [2,5,1],
               [1,3,6],
               [1,3,6]
              ])
B = np.matrix([[1,3],
               [4,2],
               [10,1]
              ])
print("A*B:\n",np.matrix(multiply(A, B)))

A*B:
 [[16  9]
 [32 17]
 [73 15]
 [73 15]]


In [3]:
# Task 7 Determinant of Matrix 

import numpy as np

# version 1 for loop
def deter_loop(M):
    (nrow,ncolumn) = M.shape
    det = 0
    for i in range(0,ncolumn):
        temp = M
        temp = np.delete(temp, (0), axis=0)
        temp = np.delete(temp, (i), axis=1)
        det += ((-1)**i)*M[0,i]*((temp[0,0]*temp[1,1])-(temp[1,0]*temp[0,1])) 
    return det


# version 2 recursion
def deter_rec(M):
    (nrow,ncolumn) = M.shape
    det = 0
    if (nrow == 1):
        return M[0,0]
    else:
        for i in range(0,ncolumn):
            temp = M
            temp = np.delete(temp, (0), axis=0)
            temp = np.delete(temp, (i), axis=1)
            det += ((-1)**i)*M[0,i]*deter_rec(temp)
    return det
    

In [4]:
import numpy as np

B = np.matrix([[1,3,1],
               [4,2,1],
               [10,1,1]
              ])
print(deter_rec(B))
print(deter_loop(B))

3
3


In [5]:
# Task 8 Minor, Cofactor, Adjoint, and Inverse
import numpy as np
# Minor
def minor(A):
    (nrow,ncolumn) = A.shape
    M = A.copy()
    for i in range(0,nrow):
        for j in range(0,ncolumn):
            temp = np.delete(A, (i), axis=0)
            temp = np.delete(temp, (j), axis=1)
            M[i,j] = deter_rec(temp)
#     print('Minor: ',np.matrix(M))
    return M


# Cofactor
def cofactor(A):
    (nrow,ncolumn) = A.shape
    M = minor(A)
    for i in range(0,nrow):
        for j in range(0,ncolumn):
            M[i,j] = M[i,j]*((-1)**(i+j))
#     print(np.matrix(M))
    return M


# adjoint
def adjoint(A):
#     print( np.matrix(transpose(cofactor(A))) )
    return transpose(cofactor(A))


# Inverse
def inverse(A):
    (nrow,ncolumn) = A.shape
    det = deter_rec(A)
    adj = adjoint(A)
    for i in range(0,nrow):
        for j in range(0,ncolumn):
            adj[i][j] = float(adj[i][j]/det) 
#     print('Inv',np.matrix(adj))
    return adj
    

In [9]:
A = np.matrix([[3,0,2],
               [1,2,1],
               [0,1,4]
              ])
minor(A)
cofactor(A)



matrix([[ 7, -4,  1],
        [ 2, 12, -3],
        [-4, -1,  6]])

In [9]:
C = np.matrix([[1,1,1,1],
               [2,0,0,2],
               [1,2,1,2],
               [2,2,1,1]
              ])

B = np.matrix([[3,0,2],
               [2,0,-2],
               [0,1,1]
              ])

# print( np.matrix(inverse(B)) )
print( 'Inv of C:\n',np.matrix(inverse(C)) )

Inv of C:
 [[-0.    0.25 -0.5   0.5 ]
 [-1.   -0.25  0.5   0.5 ]
 [ 2.   -0.25 -0.5  -0.5 ]
 [-0.    0.25  0.5  -0.5 ]]


In [11]:
deter_rec(C)

-4