In [4]:
# Task 1: Row Operation

def row_operation(m):
    [row,col] = m.shape
    nr = row
    calM = m.copy()
    v = 0
    
    # Row operaration
    for i in range(nr-1, 0, -1):
        for c in range(v,nr-1):
            fac = calM[c,i]/calM[c+1,i]
            new_eq = calM[c,:] - calM[c+1,:]*fac
            calM = np.append(calM, new_eq, axis=0)
            print("Operates ({})-({}):".format(c+1, c+2))
            print(calM[np.shape(calM)[0]-1,:])
            v += 1
        v += 1
        [nr,nc] = calM.shape
    
    print("\nThe result of row operation involves new equations:")
    print(calM)
    
    result = np.zeros((row,1)) # store the solution [a, b, c]
#     print(result)
    a = 0
    
    # Back substitution 
    for j in range(nr-1, 0, -2):
        
        sum_of_prod = 0
        for x in range(0,row):
            prod = calM[j,x]*result[x]
            sum_of_prod += prod
            
#         print("sum: ",sum_of_prod)
        result[a] = (calM[j,nc-1] - sum_of_prod)/calM[j,a]
#         print(result[a])
        a += 1
    
    return result


In [5]:
import numpy as np
import math
# 2x + y + z = 10
# 3x + 2y + 3z = 18
# x + 4y + 9z = 16
M = np.matrix([
    [2., 1., 1., 10.],
    [3., 2., 3., 18.],
    [1., 4., 9., 16.]
    ])

In [6]:
print("Task 1: Row Operation\n")
print("Original matrix of 3 equations: ")
print(M)
row_operation(M)

Task 1: Row Operation

Original matrix of 3 equations: 
[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]]
Operates (1)-(2):
[[1.         0.33333333 0.         4.        ]]
Operates (2)-(3):
[[ 2.66666667  0.66666667  0.         12.66666667]]
Operates (4)-(5):
[[-0.33333333  0.          0.         -2.33333333]]

The result of row operation involves new equations:
[[ 2.          1.          1.         10.        ]
 [ 3.          2.          3.         18.        ]
 [ 1.          4.          9.         16.        ]
 [ 1.          0.33333333  0.          4.        ]
 [ 2.66666667  0.66666667  0.         12.66666667]
 [-0.33333333  0.          0.         -2.33333333]]


array([[ 7.],
       [-9.],
       [ 5.]])

In [7]:
# Determinant (recursion)
def deter_rec(M):
    (nrow,ncolumn) = M.shape
    det = 0
    if (nrow == 1):
        return M[0,0]
    else:
        for i in range(0,ncolumn):
            temp = M
            temp = np.delete(temp, (0), axis=0)
            temp = np.delete(temp, (i), axis=1)
            det += ((-1)**i)*M[0,i]*deter_rec(temp)
    return det

# Matrix Transpose
def transpose(M):
    (nrow,ncolumn) = M.shape
    a = np.empty((nrow,ncolumn)) # store the result
    for i in range(0,nrow):
        for j in range(0,ncolumn):
            a[j,i] = M[i,j]
    # end-loop
    return a

# Minor
def minor(A):
    (nrow,ncolumn) = A.shape
    M = A.copy()
    for i in range(0,nrow):
        for j in range(0,ncolumn):
            temp = np.delete(A, (i), axis=0)
            temp = np.delete(temp, (j), axis=1)
            M[i,j] = deter_rec(temp)
#     print('Minor: ',np.matrix(M))
    return M


# Cofactor
def cofactor(A):
    (nrow,ncolumn) = A.shape
    M = minor(A)
    for i in range(0,nrow):
        for j in range(0,ncolumn):
            M[i,j] = M[i,j]*((-1)**(i+j))
#     print(np.matrix(M))
    return M


# adjoint (transpose of cofactor)
def adjoint(A):
#     print( np.matrix(transpose(cofactor(A))) )
    return transpose(cofactor(A))


# Inverse (adj/det)
def inverse(A):
    (nrow,ncolumn) = A.shape
    det = deter_rec(A)
    adj = adjoint(A)
    for i in range(0,nrow):
        for j in range(0,ncolumn):
            adj[i,j] = float(adj[i,j]/det) 
#     print('Inv',np.matrix(adj))
    return adj
    

In [8]:
# Task 2: Inverse Matrix

def inv_matrix(m):
    [row,col] = m.shape
     
    A = m[:,col-1] # A = [10, 18, 16]
    B = m[:,:col-1] # B =( [2, 1, 1],[3, 2, 3],[1, 4, 9] )
    
    inv_B = inverse(B) # inv_B
    print("\nInverse of the matrix:")
    print(inv_B)
    
    X = np.zeros(row)
   
    X = np.dot(inv_B, A) # X = inv_B dot A
    
    return X
    

In [9]:
print("Task 2: Inverse Matrix\n")
print("Original matrix of 3 equations: ")
print(M)
inv_matrix(M)

Task 2: Inverse Matrix

Original matrix of 3 equations: 
[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]]

Inverse of the matrix:
[[-3.   2.5 -0.5]
 [12.  -8.5  1.5]
 [-5.   3.5 -0.5]]


matrix([[ 7.],
        [-9.],
        [ 5.]])

In [10]:
import numpy as np
import math

# 2x - 5y = 15
# 3x + y = 31
F = np.matrix([
    [2., -5., 15.],
    [3., 1., 31.]
])

# 2x + y + z = 10
# 3x + 2y + 3z = 18
# x + 4y + 9z = 16
M = np.matrix([
    [2., 1., 1., 10.],
    [3., 2., 3., 18.],
    [1., 4., 9., 16.]
    ])

# w + 2x + y + 4z = 13
# 2w + 0x + 4y + 3z = 28
# 4w + 2x + 2y + z = 20
# -3w + x + 3y + 2z = 6
H = np.matrix([
    [1., 2., 1., 4., 13.],
    [2., 0., 4., 3., 28.],
    [4., 2., 2., 1., 20.],
    [-3., 1., 3., 2., 6.]
])

In [5]:
# Task 3: Gauss Elimination Method

# Forward Elimination

def fw_elim_for(m):
    (nrow, ncol) = np.shape(m)
    calM = m.copy()
    c = 1

    for i in range(0, ncol-1):
        for j in range(i+1, nrow):
            fac = calM[j,i]/calM[i,i]
#             print(fac)
            calM[j,:] = calM[j,:] - calM[i,:]*fac
            print("#{}:".format(c))
            c += 1
            print(calM)
            
    return calM


def fw_elim_rec(m):
    (nrow, ncol) = np.shape(m)
    calM = m.copy()
    
    if(nrow == 1):
        pass
    else:
        for i in range(0, nrow-1):
            fac = calM[i+1,0]/calM[0,0]
            calM[i+1,:] = calM[i+1,:] - calM[0,:]*fac
        
        temp = fw_elim_rec(calM[1:nrow,1:ncol])
        calM[1:nrow,1:ncol] = temp
            
    return calM       


In [6]:
# Task 3: Gauss Elimination Method

# Back Substitution

def Back_sub_for(m):
    (nrow, ncol) = np.shape(m)
    calM = m.copy()
    
    result = np.zeros(nrow)
    
    for i in range(nrow-1, -1, -1):
        
        sum_of_prod = 0
        for j in range(nrow-1, i-1, -1):
            prod = calM[i,j]*result[j]
            sum_of_prod += prod
        
        result[i] = (calM[i,ncol-1] - sum_of_prod)/calM[i,i]
            
    return result
    

In [13]:
print("Task 3: Gauss Elimination Method\n")
print("Original matrix of 3 equations: ")
print(F)
result_for = fw_elim_for(F)
print("Using for-loop:")
print(result_for)
result_rec = fw_elim_rec(F)
print("\nUsing recursive:")
print(result_rec)

Back_sub_for(result_rec)

Task 3: Gauss Elimination Method

Original matrix of 3 equations: 
[[ 2. -5. 15.]
 [ 3.  1. 31.]]
#1:
[[ 2.  -5.  15. ]
 [ 0.   8.5  8.5]]
Using for-loop:
[[ 2.  -5.  15. ]
 [ 0.   8.5  8.5]]

Using recursive:
[[ 2.  -5.  15. ]
 [ 0.   8.5  8.5]]


array([10.,  1.])

In [317]:
print("Task 3: Gauss Elimination Method\n")
print("Original matrix of 3 equations: ")
print(M)
result_for = fw_elim_for(M)
print("Using for-loop:")
print(result_for)
result_rec = fw_elim_rec(M)
print("\nUsing recursive:")
print(result_rec)

Back_sub_for(result_rec)

Task 3: Gauss Elimination Method

Original matrix of 3 equations: 
[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]]
#1:
[[ 2.   1.   1.  10. ]
 [ 0.   0.5  1.5  3. ]
 [ 1.   4.   9.  16. ]]
#2:
[[ 2.   1.   1.  10. ]
 [ 0.   0.5  1.5  3. ]
 [ 0.   3.5  8.5 11. ]]
#3:
[[  2.    1.    1.   10. ]
 [  0.    0.5   1.5   3. ]
 [  0.    0.   -2.  -10. ]]
Using for-loop:
[[  2.    1.    1.   10. ]
 [  0.    0.5   1.5   3. ]
 [  0.    0.   -2.  -10. ]]

Using recursive:
[[  2.    1.    1.   10. ]
 [  0.    0.5   1.5   3. ]
 [  0.    0.   -2.  -10. ]]


array([ 7., -9.,  5.])

In [8]:
import numpy as np
import math

M = np.matrix([
    [6., 15., 55., 152.6],
    [15., 55., 225., 585.6],
    [55., 225., 979., 2488.8]
    ])

In [9]:
print("Task 3: Gauss Elimination Method\n")

print("Original matrix of 3 equations: ")
print(M)
result_for = fw_elim_for(M)
print("Using for-loop:")
print(result_for)
result_rec = fw_elim_rec(M)
print("\nUsing recursive:")
print(result_rec)

Back_sub_for(result_rec)

Task 3: Gauss Elimination Method

Original matrix of 3 equations: 
[[   6.    15.    55.   152.6]
 [  15.    55.   225.   585.6]
 [  55.   225.   979.  2488.8]]
#1:
[[   6.    15.    55.   152.6]
 [   0.    17.5   87.5  204.1]
 [  55.   225.   979.  2488.8]]
#2:
[[   6.           15.           55.          152.6       ]
 [   0.           17.5          87.5         204.1       ]
 [   0.           87.5         474.83333333 1089.96666667]]
#3:
[[  6.          15.          55.         152.6       ]
 [  0.          17.5         87.5        204.1       ]
 [  0.           0.          37.33333333  69.46666667]]
Using for-loop:
[[  6.          15.          55.         152.6       ]
 [  0.          17.5         87.5        204.1       ]
 [  0.           0.          37.33333333  69.46666667]]

Using recursive:
[[  6.          15.          55.         152.6       ]
 [  0.          17.5         87.5        204.1       ]
 [  0.           0.          37.33333333  69.46666667]]


array([2.47857143, 2.35928571, 1.86071429])

In [319]:
# Task 4: Cramer's Rule Method

def cramer(m):
    (nrow, ncol) = np.shape(m)
    A = m[:,:ncol-1]
    print(A)
    B = m[:,ncol-1]
    print(B)
    detA = deter_rec(A)
    
    X = np.zeros(nrow)
    
    for i in range(0, ncol-1):
        temp = A.copy()
        temp[:,i] = B
        X[i] = deter_rec(temp)/detA
    
    return X
        

In [297]:
cramer(F)

[[ 2 -5]
 [ 3  1]]
[[15]
 [31]]


array([10.,  1.])

In [296]:
cramer(M)

[[2. 1. 1.]
 [3. 2. 3.]
 [1. 4. 9.]]
[[10.]
 [18.]
 [16.]]


array([ 7., -9.,  5.])

In [298]:
cramer(H)

[[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
[[13]
 [28]
 [20]
 [ 6]]


array([ 3., -1.,  4.,  2.])

In [351]:
# Task 5: Pivoting

def partial_piv(m):
    (nrow, ncol) = np.shape(m)
    calM = m.copy()
    temp = calM[0,0]
    for i in range(1,nrow):
        temp = calM[i,:].copy()
        t = calM[i,0]
        j = i
        while(j > 0 and calM[j-1,0] < t):
            calM[j,:] = calM[j-1,:]
            j -= 1
        calM[j,:] = temp
                
    return calM


In [355]:
C = np.matrix([
    [0., 2., 5., 1.],
    [2., 1., 1., 1.],
    [3., 1., 0., 2.]
])
print("Original:")
print(C)
partial_piv(C)

Original:
[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [3. 1. 0. 2.]]


matrix([[3., 1., 0., 2.],
        [2., 1., 1., 1.],
        [0., 2., 5., 1.]])